import * as Silk from "@silk";

export type FontProps = {
    font?: Silk.CssProps["font"];
    fontFamily?: Silk.CssProps["fontFamily"];
    fontFeatureSettings?: Silk.CssProps["fontFeatureSettings"];
    fontKerning?: Silk.CssProps["fontKerning"];
    fontLanguageOverride?: Silk.CssProps["fontLanguageOverride"];
    fontOpticalSizing?: Silk.CssProps["fontOpticalSizing"];
    fontPalette?: Silk.CssProps["fontPalette"];
    fontSize?: Silk.CssProps["fontSize"];
    fontSizeAdjust?: Silk.CssProps["fontSizeAdjust"];
    fontSmooth?: Silk.CssProps["fontSmooth"];
    fontStretch?: Silk.CssProps["fontStretch"];
    fontStyle?: Silk.CssProps["fontStyle"];
    fontSynthesis?: Silk.CssProps["fontSynthesis"];
    fontSynthesisPosition?: Silk.CssProps["fontSynthesisPosition"];
    fontSynthesisSmallCaps?: Silk.CssProps["fontSynthesisSmallCaps"];
    fontSynthesisStyle?: Silk.CssProps["fontSynthesisStyle"];    
    fontSynthesisWeight?: Silk.CssProps["fontSynthesisWeight"];
    fontVariant?: Silk.CssProps["fontVariant"];
    fontVariantAlternates?: Silk.CssProps["fontVariantAlternates"];
    fontVariantCaps?: Silk.CssProps["fontVariantCaps"];
    fontVariantEastAsian?: Silk.CssProps["fontVariantEastAsian"];
    fontVariantEmoji?: Silk.CssProps["fontVariantEmoji"];
    fontVariantLigatures?: Silk.CssProps["fontVariantLigatures"];
    fontVariantNumeric?: Silk.CssProps["fontVariantNumeric"];
    fontVariantPosition?: Silk.CssProps["fontVariantPosition"];
    fontVariationSettings?: Silk.CssProps["fontVariationSettings"];
    fontWeight?: Silk.CssProps["fontWeight"];
};