export type MathErrorCode =
    | "MATH.ERR_ARITHMETIC_UNDERFLOW"
    | "MATH.ERR_ARITHMETIC_OVERFLOW"
    | "MATH.ERR_NOT_FINITE"
    | "MATH.ERR_NOT_A_NUMBER"
    | "MATH.ERR_NEGATIVE_EXPONENT_ZERO_BASE"
    | "MATH.ERR_FRACTIONAL_EXPONENT_NEGATIVE_BASE"
    | "MATH.ERR_DIVISION_BY_ZERO";