import {
    type Error
} from "@root";

type NetworkErrorCode =
    | "NETWORK.ERR_UNKNOWN"
    | "NETWORK.CLIENT_ERR_BAD_REQUEST"
    | "NETWORK.CLIENT_ERR_UNAUTHORIZED"
    | "NETWORK.CLIENT_ERR_PAYMENT_REQUIRED"
    | "NETWORK.CLIENT_ERR_FORBIDDEN"
    | "NETWORK.CLIENT_ERR_NOT_FOUND"
    | "NETWORK.CLIENT_ERR_METHOD_NOT_ALLOWED"
    | "NETWORK.CLIENT_ERR_NOT_ACCEPTABLE"
    | "NETWORK.CLIENT_ERR_PROXY_AUTHNTICATION_REQUIRED"
    | "NETWORK.CLIENT_ERR_REQUEST_TIMEOUT"
    | "NETWORK.CLIENT_ERR_CONFLICT"
    | "NETWORK.CLIENT_ERR_GONE"
    | "NETWORK.CLIENT_ERR_LENGTH_REQUIRED"
    | "NETWORK.CLIENT_ERR_PRECONDITION_FAILED"
    | "NETWORK.CLIENT_ERR_CONTENT_TOO_LARGE"
    | "NETWORK.CLIENT_ERR_URI_TOO_LONG"
    | "NETWORK.CLIENT_ERR_UNSUPPORTED_MEDIA_TYPE"
    | "NETWORK.CLIENT_ERR_RANGE_NOT_SATISFIABLE"
    | "NETWORK.CLIENT_ERR_EXPECTATION_FAILED"
    | "NETWORK.CLIENT_ERR_IM_A_TEAPOT"
    | "NETWORK.CLIENT_ERR_MISDIRECT_REQUEST"
    | "NETWORK.CLIENT_ERR_UNPROCESSABLE_CONTENT"
    | "NETWORK.CLIENT_ERR_LOCKED"
    | "NETWORK.CLIENT_ERR_FAILED_DEPENDENCY"
    | "NETWORK.CLIENT_ERR_TOO_EARLY"
    | "NETWORK.CLIENT_ERR_UPGRADE_REQUIRED"
    | "NETWORK.CLIENT_ERR_PRECONDITION_REQUIRED"
    | "NETWORK.CLIENT_ERR_TOO_MANY_REQUESTS"
    | "NETWORK.CLIENT_ERR_REQUEST_HEADER_FIELDS_TOO_LARGE"
    | "NETWORK.CLIENT_ERR_UNAVAILABLE_FOR_LEGAL_REASONS"
    | "NETWORK.SERVER_ERR"
    | "NETWORK.SERVER_ERR_NOT_IMPLEMENTED"
    | "NETWORK.SERVER_ERR_BAD_GATEWAY"
    | "NETWORK.SERVER_ERR_SERVICE_UNAVAILABLE"
    | "NETWORK.SERVER_ERR_GATEWAY_TIMEOUT"
    | "NETWORK.SERVER_ERR_HTTP_VERSION_NOT_SUPPORTED"
    | "NETWORK.SERVER_ERR_VARIANT_ALSO_NEGOTIATES"
    | "NETWORK.SERVER_ERR_INSUFFICIENT_STORAGE"
    | "NETWORK.SERVER_ERR_LOOP_DETECTED"
    | "NETWORK.SERVER_ERR_NOT_EXTENDED"
    | "NETWORK.SERVER_ERR_AUTHENTICATION_REQUIRED";

    ; 

type NetworkError =
    & Error<NetworkErrorCode>
    & {
    statusCode: bigint;
};

export {
    type NetworkErrorCode,
    type NetworkError
};