export type VmErrorCode =
    /// Generic
    | "VM.ERR_UNKNOWN"
    | "VM.ERR_NOT_IMPLEMENTED"
    | "VM.ERR_UNSUPPORTED_OPERATION"
    | "VM.ERR_NETWORK_FAULT"
    | "VM.ERR_SERVER_FAULT"
    | "VM.ERR_TIMEOUT"
    | "VM.ERR_BAD_DATA"
    | "VM.ERR_CANCELLED"
    | "VM.ERR_INVALID_RESPONSE"

    /// Operational
    | "VM.ERR_BUFFER_OVERRUN"
    | "VM.ERR_NUMERIC_FAULT"

    /// Argument
    | "VM.ERR_INVALID_ARGUMENT"
    | "VM.ERR_MISSING_ARGUMENT"
    | "VM.ERR_UNEXPECTED_ARGUMENT"

    /// Blockchain
    | "VM.ERR_CALL_EXCEPTION"
    | "VM.ERR_INSUFFICIENT_FUNDS"
    | "VM.ERR_NONCE_EXPIRED"
    | "VM.ERR_REPLACEMENT_UNDERPRICED"
    | "VM.ERR_TRANSACTION_REPLACED"
    | "VM.ERR_UNCONFIGURED_NAME"
    | "VM.ERR_OFFCHAIN_FAULT"

    /// User Interaction
    | "VM.ERR_ACTION_REJECTED";